version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


